name: Deploy Python Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Replace with your Python version

      - name: Install AWS CLI
        run: |
          pip3 install awscli
          aws --version
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}   # Change to your region
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Create Deployment Package
        run: |
          mkdir package
          pip3 install -r requirements.txt --target ./package
          cd package
          zip -r ../deployment-package.zip .
          cd ..
          ls lambda_function.py
          zip deployment_package.zip lambda_function.py
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}   # Change to your region

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name processInboundEmails \
            --zip-file fileb://deployment-package.zip \
            --region $AWS_REGION
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
